version: '2.2'
services:
    web:
        build: .
        ports:
        - "5000:5000"
        volumes:
        - .:/app
        env_file: 
        - .env
    tests:
        build: .
        command: -m pytest -vv
        volumes:
            - .:/app
        links:
            - web
    update-script:
        build: .
        command: update_ratings.py
        volumes:
            - .:/app
        links:
            - web
        env_file: 
            - .env